<?php

namespace Database\Seeders;

use App\Models\Employee;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         Employee::insert([
            [
                'employee_type_id' => 1,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 1,
                'user_id' => 1,
                'identity_number' => '197506252021211003',
                'slug' => 'subono-s-t-m-t',
                'name' => 'Subono, S.T.,M.T',
                'gender' => 'male',
                'image' => 'subono.jpg',
                'nidn'=> '0025067508',
                'email'=> 'subono@poliwangi.ac.id',
                'phone_number'=> '087859576210',
                'address'=> 'Jl. Bunga Kumis Kucing no. 20 Rt/Rw 004/002 Jatimulyo - Lowokwaru Malang 65141',
                "id_sdm" => "cf7bb033-168b-4507-8c5d-7dacc57d5b73",

            ],
            [
                'employee_type_id' => 1,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 2,
                'user_id' => 1,
                'identity_number' => '197509272021211002',
                'slug' => 'herman-yuliandoko-s-t-m-t',
                'name' => 'Herman Yuliandoko, S.T.,M.T',
                'gender' => 'male',
                'image' => 'herman.jpg',
                'nidn'=> '0027097504',
                'email'=> 'herman.yuliandoko@poliwangi.ac.id',
                'phone_number'=> '081 334 436 478',
                'address'=> 'Perum Citra Garden Blok F1, Lemahbang Dewo, Rogojampi',
                "id_sdm" => "86ca7be5-6aa7-4c13-b195-14670f3db7f3",
            ],
            [
                'employee_type_id' => 1,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 1,
                'user_id' => 1,
                'identity_number' => '197601222021211001',
                'slug' => 'mohamad-dimyati-ayatullah-s-t-m-kom',
                'name' => 'Mohamad Dimyati Ayatullah, S.T.,M.Kom',
                'gender' => 'male',
                'image' => 'dimyati.jpg',
                'nidn'=> '0722017601',
                'email'=> 'dimyati@poliwangi.ac.id',
                'phone_number'=> '081 233 991 84',
                'address'=> 'Dusun Kraja 001/001 Sumbersari - Srono Banyuwangi 68471',
                "id_sdm" => "12c99923-e00e-48f2-869a-da35dd29123c",
            ],
            [
                'employee_type_id' => 1,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 3,
                'user_id' => 1,
                'identity_number' => '197704042021211004',
                'slug' => 'dedy-hidayat-kusuma-s-t-m-cs',
                'name' => 'Dedy Hidayat Kusuma, S.T.,M.Cs',
                'gender' => 'male',
                'image' => 'dedy.jpg',
                'nidn'=> '0004047712',
                'email'=> 'dedy@poliwangi.ac.id',
                'phone_number'=> '087755527517',
                'address'=> 'Sumber Kepuh Rt/Rw 003/001 Kedungwungu - Tegaldlimo Banyuwangi 68484',
                "id_sdm" => "04cd36ec-14eb-42af-8cdb-339f4d24737e",
            ],
            [
                'employee_type_id' => 1,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 2,
                'user_id' => 1,
                'identity_number' => '197806132014041001',
                'slug' => 'muhammad-fuad-alharis-s-t-m-t',
                'name' => 'Muhammad Fuad Alharis, S.T.,M.T',
                'gender' => 'male',
                'image' => 'fuad.jpg',
                'nidn'=> '0713067802',
                'email'=> 'f_haris@poliwangi.ac.id',
                'phone_number'=> '081 234 619 898',
                'address'=> 'Perum Brawijaya Regency Jl. Basuki Rahmat Gg.Mangga No.12 Rt/Rw 002/004 Lateng - Banyuwangi 68413',
                "id_sdm" => "0475fc50-9240-4689-8cac-9598a689ed49",
            ],
            [
                'employee_type_id' => 1,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 1,
                'user_id' => 1,
                'identity_number' => '198010222015041001',
                'slug' => 'i-wayan-suardinata-s-kom-m-kot',
                'name' => 'I Wayan Suardinata, S.Kom.,M.T',
                'gender' => 'male',
                'image' => 'wayan.jpg',
                'nidn'=> '0022108005',
                'email'=> 'wayan.suardinata@poliwangi.ac.id',
                'phone_number'=> '085736577864',
                'address'=> 'Jalan Prabu loro 525A Kelurahan Bakungan kecamtan Glagah',
                "id_sdm" => "a5508e4a-7c84-4030-930a-e0026a484ba9",
            ],
            [
                'employee_type_id' => 1,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 2,
                'user_id' => 1,
                'identity_number' => '198301192021211006',
                'slug' => 'moh-nur-shodiq-s-t-m-t',
                'name' => 'Moh. Nur Shodiq, S.T.,M.T',
                'gender' => 'male',
                'image' => 'shodiq.jpg',
                'nidn'=> ' 0019018307',
                'email'=> 'noer.shodiq@poliwangi.ac.id',
                'phone_number'=> '085 236 675 444',
                'address'=> 'Kampungtimur 001/004 Trigonco - Asembagus Situbondo 68373',
                "id_sdm" => "8a873502-fa06-4e31-a697-6de9906a0fc1",
            ],
            [
                'employee_type_id' => 1,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 3,
                'user_id' => 1,
                'identity_number' => '198310202014042001',
                'slug' => 'eka-mistiko-rini-s-kom-m-kom',
                'name' => 'Eka Mistiko Rini, S.Kom.,M.Kom',
                'gender' => 'female',
                'image' => 'eka.jpg',
                'nidn'=> '0720108301',
                'email'=> 'ekamrini@poliwangi.ac.id',
                'phone_number'=> '081 913 922 224',
                'address'=> 'Dusun WatuUlo Rt/Rw 004/002 Rejosari - Glagah Banyuwangi 68432',
                "id_sdm" => "51721c9b-fe38-468f-a496-4ae9280b1bd5",
            ],
            [
                'employee_type_id' => 1,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 1,
                'user_id' => 1,
                'identity_number' => '198311052015041001',
                'slug' => 'devit-suwardiyanto-s-si-m-t',
                'name' => 'Devit Suwardiyanto, S.Si.,M.T',
                'gender' => 'male',
                'image' => 'devit.jpg',
                'nidn'=> '0705118304',
                'email'=> 'ds@poliwangi.ac.id',
                'phone_number'=> '081 135 706 83',
                'address'=> 'Perum Mendut Hijau Blok F No 3, Tamanbaru, Banyuwangi',
                "id_sdm" => "cb4b79bc-162e-4ead-b339-4d35288cf37a",
            ],
            [
                'employee_type_id' => 1,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 1,
                'user_id' => 1,
                'identity_number' => '198403052021212004',
                'slug' => 'dianni-yusuf-s-kom-m-kom',
                'name' => 'Dianni Yusuf, S.Kom.,M.Kom',
                'gender' => 'female',
                'image' => 'dianni.jpg',
                'nidn'=> '0705038402',
                'email'=> 'dianniyusuf@poliwangi.ac.id',
                'phone_number'=> '082328333399',
                'address'=> 'Dsn. Gembolo Rt/Rw 01/01 Purwodadi - Gambiran Banyuwangi 68486',
                "id_sdm" => "5a386c83-63f5-46a2-8bca-0b94104b0324",
            ],
            [
                'employee_type_id' => 1,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 1,
                'user_id' => 1,
                'identity_number' => '198403112019031005',
                'slug' => 'endi-sailul-haq-s-t-m-kom',
                'name' => 'Endi Sailul Haq, S.T.,M.Kom',
                'gender' => 'female',
                'image' => 'endi.jpg',
                'nidn'=> '0015038402',
                'email'=> 'esailulhaq@gmail.com',
                'phone_number'=> '081 336 851 513',
                'address'=> 'Dusun Kebonrejo Rt/Rw 003/001 Alasrejo Wongsorejo - Banyuwangi 68453',
                "id_sdm" => "269ecb19-0475-414f-ab68-dce1abd719f9",
            ],
            [
                'employee_type_id' => 1,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 1,
                'user_id' => 1,
                'identity_number' => '198404032019032012',
                'slug' => 'vivien-arief-wardhany-s-t-m-t',
                'name' => 'Vivien Arief Wardhany, S.T.,M.T',
                'gender' => 'female',
                'image' => 'vivien.jpg',
                'nidn'=> '0003048406',
                'email'=> 'vivien.wardhany@poliwangi.ac.id',
                'phone_number'=> '0813-3106-8658',
                'address'=> 'Perum Citra Garden Blok C-20, Dusun Satriyan 002/004 Lemahbangdewo Rogojampi - Banyuwangi 68462',
                "id_sdm" => "d8722444-05af-459f-838d-6d905af81770",
            ],
            [
                'employee_type_id' => 1,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 1,
                'user_id' => 1,
                'identity_number' => '2013.36.106',
                'slug' => 'farizqi-panduardi-s-st-m-t',
                'name' => 'Farizqi Panduardi, S.ST.,M.T',
                'gender' => 'male',
                'image' => 'farizqi.jpg',
                'nidn'=> '0005038604',
                'email'=> 'akufarisqi@poliwangi.ac.id',
                'phone_number'=> '082244680800',
                'address'=> 'Jl.S.Parman 33 Gardenia Estate G97',
                "id_sdm" => "d2d07dff-8838-489f-9c2e-b9909717280",
            ],
            [
                'employee_type_id' => 1,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 1,
                'user_id' => 1,
                'identity_number' => '199004192018031001',
                'slug' => 'junaedi-adi-prasetyo-s-st-m-sc',
                'name' => 'Junaedi Adi Prasetyo, S.ST.,M.Sc',
                'gender' => 'male',
                'image' => 'junaidi.jpg',
                'nidn'=> '0019049005',
                'email'=> 'junaedi.prasetyo@poliwangi.ac.id',
                'phone_number'=> '082333312244',
                'address'=> 'Jl. Tirtosari Blok D No 12 Landungsari Malang 65151',
                "id_sdm" => "a8e1bc04-962f-4788-9651-bf573039e3f2",
            ],
            [
                'employee_type_id' => 1,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 1,
                'user_id' => 1,
                'identity_number' => '199009052019031024',
                'slug' => 'sepyan-purnama-kristanto-s-kom-m-kom',
                'name' => 'Sepyan Purnama Kristanto, S.Kom.,M.Kom',
                'gender' => 'male',
                'image' => 'sepyan.jpeg',
                'nidn'=> '0005099006',
                'email'=> 'Sepyan@poliwangi.ac.id',
                'phone_number'=> '085237516017',
                'address'=> 'Jl. Temuguruh Rt.03 Rw.01 Resomulyo  Banyuwangi',
                "id_sdm" => "c06c52e8-2d24-4417-898d-1b43fe7eb08f",
            ],
            [
                'employee_type_id' => 1,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 1,
                'user_id' => 1,
                'identity_number' => '199010052014041002',
                'slug' => 'alfin-hidayat-s-t-m-t',
                'name' => 'Alfin Hidayat, S.T.,M.T',
                'gender' => 'male',
                'image' => 'alfin.jpg',
                'nidn'=> '0005109001',
                'email'=> 'alfin.hidayat@poliwangi.ac.id',
                'phone_number'=> '085731147608',
                'address'=> 'Dsn.Krajan 02/01 Blambangan - Muncar Banyuwangi 68472',
                "id_sdm" => "411b2d24-24ad-4968-9caf-fb8a51656956",
            ],
            [
                'employee_type_id' => 1,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 1,
                'user_id' => 1,
                'identity_number' => '199104202018031002',
                'slug' => 'alif-akbar-fitriawan-s-pd-m-kom',
                'name' => 'Alif Akbar Fitrawan, S.Pd.,M.Kom',
                'gender' => 'male',
                'image' => 'alif.jpg',
                'nidn'=> '0020049102',
                'email'=> 'alifakbarfitrawan@gmail.com',
                'phone_number'=> '085646421106',
                'address'=> 'Perumahan Pengantigan Indah Blok BC-02 Rogojampi',
                "id_sdm" => "",
            ],
            [
                'employee_type_id' => 1,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 1,
                'user_id' => 1,
                'identity_number' => '199203302019031012',
                'slug' => 'lutfi-hakim-s-pd-m-t',
                'name' => 'Lutfi Hakim, S.Pd.,M.T',
                'gender' => 'male',
                'image' => 'lutfi.jpeg',
                'nidn'=> '0030039202',
                'email'=> 'Lutfi@poliwangi.ac.id',
                'phone_number'=> '085330161514',
                'address'=> 'Jl, kepodang no 11 Rw 1rw 2kalirejo kabat banyuwangi',
                "id_sdm" => "0e60a0f1-d57c-4a95-8b6f-323f78edb607",
            ],
            [
                'employee_type_id' => 1,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 1,
                'user_id' => 1,
                'identity_number' => '2010.36.048',
                'slug' => 'agus-priyo-utomo-s-st-mtr-kom',
                'name' => 'Agus Priyo Utomo, S.ST.,M.Tr.Kom',
                'gender' => 'male',
                'image' => 'agus.jpeg',
                'nidn'=> '0027088704',
                'email'=> 'agusp@poliwangi.ac.id',
                'phone_number'=> '085 731 311 399',
                'address'=> 'Jl. RW Monginsidi 14 - Banyuwangi 68416',
                "id_sdm" => "fa32bd47-822a-494f-85a1-44413ecb3b11",
            ],
            [
                'employee_type_id' => 1,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 1,
                'user_id' => 1,
                'identity_number' => '199202272020122019',
                'slug' => 'ruth-ema-febrita-s-pd-m-kom',
                'name' => 'Ruth Ema Febrita, S.Pd.,M.Kom',
                'gender' => 'female',
                'image' => 'ema.jpeg',
                'nidn'=> '0027029204',
                'email'=> 'RuthEmaFebrita@poliwangi.ac.id',
                'phone_number'=> '085259082627',
                'address'=> 'Jl. Jaksa Agusng Suprapto, gg Annur 1  no 25 B pengajuran Banywuangi',
                "id_sdm" => "19c4ad0b-7e36-49ab-9d15-0c6d85134b6f",
            ],
            [
                'employee_type_id' => 1,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 1,
                'user_id' => 1,
                'identity_number' => '2018.36.214',
                'slug' => 'galih-hendra-wibowo-s-tr-kom-m-t',
                'name' => 'Galih Hendra Wibowo, S.Tr.Kom.,M.T',
                'gender' => 'male',
                'image' => 'galih.jpg',
                'nidn'=> '0005099204',
                'email'=> 'galih@poliwangi.ac.id',
                'phone_number'=> '083831120642',
                'address'=> 'Surabaya, Jl Ahmad 3 No.15 Rt.01 RW.10 Pepe Legi Waru Sidoarjo',
                "id_sdm" => "6ea6b6c8-4b6b-4d76-8cf4-45e557cada6f",
            ],
            [
                'employee_type_id' => 1,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 1,
                'user_id' => 1,
                'identity_number' => '199209212020122021',
                'slug' => 'arum-randary-ratri-s-si-m-si',
                'name' => 'Arum Andary Ratri, S.Si.,M.Si',
                'gender' => 'female',
                'image' => 'arum.jpeg',
                'nidn'=> '0021099202',
                'email'=> 'Arumandaryratri@poliwangi.ac.id',
                'phone_number'=> '083117703473',
                'address'=> 'Dusun Krajan Barat Rt 1 Rw 1, Desa Singonjuruh Kecamatan Singonjuruh',
                "id_sdm" => "cff56fc8-6bd0-47fb-b8b1-6eda97249966",
            ],
            [
                'employee_type_id' => 1,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 1,
                'user_id' => 1,
                'identity_number' => '2021.36.248',
                'slug' => 'indira-nuansa-ratri-s-m-m-sm',
                'name' => 'Indira Nuansa Ratri, S.M.,M.SM',
                'gender' => 'female',
                'image' => 'indira.jpeg',
                'nidn'=> '',
                'email'=> 'indira.nuansaratri@poliwangi.ac.id',
                'phone_number'=> '083117703473',
                'address'=> 'Dusun Krajan Barat Rt 1 Rw 1, Desa Singonjuruh Kecamatan Singonjuruh',
                "id_sdm" => "bb5e6c12-4fee-42ff-a323-0d2d47a55f1a",
            ],
            [
                'employee_type_id' => 3,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 1,
                'user_id' => 1,
                'identity_number' => '198711032021212001',
                'slug' => 'dian-mujiani-s-e',
                'name' => 'Dian Mujiani, S.E',
                'gender' => 'female',
                'image' => 'dian.jpeg',
                'nidn'=> '',
                'email'=> 'dianmjn@poliwangi.ac.id',
                'phone_number'=> '085 333859623',
                'address'=> 'Jl. Ikan Cakalang 31 Banyuwangi',
                "id_sdm" => "10208d04-551d-43ed-ab7a-d672fbe88b35",
            ],
            [
                'employee_type_id' => 2,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 1,
                'user_id' => 1,
                'identity_number' => '198810152014041001',
                'slug' => 'fendi-hermawanto-a-md',
                'name' => 'Fendi Hermawanto, A.Md',
                'gender' => 'male',
                'image' => 'fendi.jpg',
                'nidn'=> '',
                'email'=> '',
                'phone_number'=> '',
                'address'=> '',
                "id_sdm" => "29c162a6-2eb9-4a3e-a398-5960b765e786",
            ],
            [
                'employee_type_id' => 2,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 1,
                'user_id' => 1,
                'identity_number' => '2013.36.105',
                'slug' => 'muhamad-nur-hariri-a-md',
                'name' => 'Muhammad Nur Hariri, A.Md',
                'gender' => 'male',
                'image' => 'hariri.jpg',
                'nidn'=> '',
                'email'=> 'fendihermawanto@poliwangi.ac.id',
                'phone_number'=> '087857297775',
                'address'=> 'Dusun Srono RT02/03 Kebaman Srono - Banyuwnagi 68471',
                "id_sdm" => "",
            ],
            [
                'employee_type_id' => 2,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 1,
                'user_id' => 1,
                'identity_number' => '198705032014041001',
                'slug' => 'hida-jaya-habibi-a-md',
                'name' => 'Hida Jaya Habibi, A.Md',
                'gender' => 'male',
                'image' => 'hidajaya.jpg',
                'nidn'=> '',
                'email'=> 'hidajay@poliwangi.ac.id',
                'phone_number'=> '081230557807',
                'address'=> 'Dsn. Krajan Rt 02/Rw 05 Desa Kabat Kecamatan Kabat - Banyuwangi 68461',
                "id_sdm" => "518473dd-8bba-4519-bb53-8422f2de6e8f",
            ],
            [
                'employee_type_id' => 2,
                'employee_status_id' => 1,
                'employee_program_studi_id' => 1,
                'user_id' => 1,
                'identity_number' => '2013.36.108',
                'slug' => 'nur-cholik-hasyim-a-md',
                'name' => 'Nur Cholik Hasyim, A.Md',
                'gender' => 'male',
                'image' => 'cholik.jpg',
                'nidn'=> '',
                'email'=> 'ncadvertise@gmail.com',
                'phone_number'=> '087857297775',
                'address'=> 'Dusun Srono RT02/03 Kebaman Srono - Banyuwnagi 68471',
                "id_sdm" => "",
            ],
        ]);
    }
}
